// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRUsSuLHtl7bi9sUsB5wnvND2x-1Bkl6g',
    appId: '1:566529662950:web:f988409ae77934a1af4027',
    messagingSenderId: '566529662950',
    projectId: 'messaging-app-283be',
    authDomain: 'messaging-app-283be.firebaseapp.com',
    storageBucket: 'messaging-app-283be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm8_RcxMEuz92UpncsjBoqDVlaTL4bsYA',
    appId: '1:566529662950:android:1ae6cbe35501a297af4027',
    messagingSenderId: '566529662950',
    projectId: 'messaging-app-283be',
    storageBucket: 'messaging-app-283be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4L-wdp5M5IWE64XJLZpha6MRwEhrtv0',
    appId: '1:566529662950:ios:f7a0304267f77e1faf4027',
    messagingSenderId: '566529662950',
    projectId: 'messaging-app-283be',
    storageBucket: 'messaging-app-283be.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN4L-wdp5M5IWE64XJLZpha6MRwEhrtv0',
    appId: '1:566529662950:ios:f7a0304267f77e1faf4027',
    messagingSenderId: '566529662950',
    projectId: 'messaging-app-283be',
    storageBucket: 'messaging-app-283be.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRUsSuLHtl7bi9sUsB5wnvND2x-1Bkl6g',
    appId: '1:566529662950:web:5161fddb9c815b36af4027',
    messagingSenderId: '566529662950',
    projectId: 'messaging-app-283be',
    authDomain: 'messaging-app-283be.firebaseapp.com',
    storageBucket: 'messaging-app-283be.firebasestorage.app',
  );
}
